# Generated by Django 3.1.1 on 2021-02-05 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esuits', '0022_auto_20210124_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='answermodel',
            name='char_num',
            field=models.IntegerField(blank=True, default=0, verbose_name='文字数'),
        ),
    ]
