# Generated by Django 3.1.1 on 2021-02-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esuits', '0023_answermodel_char_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='回答'),
        ),
    ]
