# Generated by Django 3.1.1 on 2021-02-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esuits', '0025_auto_20210205_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrysheetesmodel',
            name='is_editing',
            field=models.BooleanField(default=True, verbose_name='編集中'),
        ),
    ]
