# Generated by Django 3.1.1 on 2021-02-17 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esuits', '0026_auto_20210215_0105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionmodel',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='questionmodel',
            name='char_num',
        ),
    ]
